[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[doc]
title = "Eigen-Bridge"
description = "Proof of concept implementation of a cross-chain bridge secured by EigenLayer AVS"
authors = [""]

